language: c
git:
  submodules: false
  depth: 250
os:
 - osx
 - linux

sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
    - common_py_deps="conda-build"
    - PACKAGENAME=molPX
    - PYTHONHASHSEED=0
    - OMP_NUM_THREADS=2
  matrix:
    - CONDA_PY=3.5 CONDA_NPY=1.11
    - CONDA_PY=3.6 CONDA_NPY=1.12

before_install:
- devtools/ci/travis/install_miniconda.sh
- conda config --set always_yes true
- conda config --add channels conda-forge
- conda install -q $common_py_deps

script:
- conda build -q --no-long-test-prefix devtools/conda-recipe

after_success:
- bash <(curl -s https://codecov.io/bash) -f /tmp/coverage.xml

