language: python
os:
 - linux

sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
    - common_py_deps="conda-build=2.0.1"
    - PACKAGENAME=pyemma
    - ORGNAME=omnia
    - PYTHONHASHSEED=0
    - OMP_NUM_THREADS=2
  matrix:
    - CONDA_PY=2.7 CONDA_NPY=1.11
    - CONDA_PY=3.4 CONDA_NPY=1.10
    - CONDA_PY=3.5 CONDA_NPY=1.11

before_install:
- devtools/ci/travis/install_miniconda.sh
- conda config --add channels bioconda

script:
- python setup.py -q install
