language: python
os:
 - linux

sudo: false

env:
  matrix:
    - CONDA_PY=2.7 CONDA_NPY=1.11
    - CONDA_PY=3.4 CONDA_NPY=1.10
    - CONDA_PY=3.5 CONDA_NPY=1.11

before_install:
- devtools/ci/travis/install_miniconda.sh
- conda config --add channels bioconda

script:
- python setup.py -q install
