package:
  name: molpx
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  number: 0 # remember to change this manually every build until automated
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - nglview >=1
    - pyemma
    - scikit-learn
    - notebook
    - ipympl

test:
  source_files:
    - .coveragerc
    - molpx/notebooks/*
  requires:
    - pip
    - pytest ==3.2.5
    - pytest-cov ==2.5.1
    - coverage ==4.4.2
    - nbval ==0.7
  imports:
    - molpx
  commands:
    - pytest -vv --pyargs molpx --cov=molpx --cov-report=xml --current-env --nbval-lax
    #- pytest -vv --pyargs molpx --cov=molpx --current-env --cov-report=xml
    #- ls -R
    #- pwd
    #- pytest -vv --current-env --nbval-lax
    - python -c "import shutil, os; shutil.copy('coverage.xml', os.path.expanduser('~'))"
about:
  home: https://github.com/gph82/projection_explorer
  license: GNU Lesser Public License v3+
  summary: "molPX: Molecular Projection Explorer"


