package:
  name: molpx
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: 0.1.0
  #{{ GIT_DESCRIBE_TAG[1:] + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  number: 0 # remember to change this manually every build until automated
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - nglview >=v0.6.2.2
    - pyemma
    - scikit-learn
    - notebook

test:
  requires:
    - pytest
    - pytest-cov
    - nbconvert
  imports:
    - molpx
  commands:
    - pytest --pyargs molpx
    - echo "c.ExecutePreprocessor.timeout = -1" > jupyter_nbconvert_config.py
    #- ls $(python -c "from __future__ import print_function; import pkg_resources; print(pkg_resources.resource_filename('molpx', 'notebooks/'))")
    - jupyter nbconvert --config jupyter_nbconvert_config.py --execute $(python -c "from __future__ import print_function; import pkg_resources; print(pkg_resources.resource_filename('molpx', 'notebooks/Projection_Explorer.ipynb'))") --ExecutePreprocessor.kernel_name=python
about:
  home: https://github.com/gph82/projection_explorer
  license: GNU Lesser Public License v3+
  summary: "molPX: Molecular Projection Explorer"


