package:
  name: molpx
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  number: 0 # remember to change this manually every build until automated
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - nglview >=0.6.2.2
    - pyemma
    - scikit-learn
    - notebook

test:
  source_files:
    - .coveragerc
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - molpx
  commands:
    - pip install git+https://github.com/computationalmodelling/nbval
    - pip install nglview==1.0b5
    - pytest -vv --pyargs molpx --cov=molpx --cov-report=xml --current-env #--nbval-lax
   # --ignore=TICA_Fast_Folding_Analysis.ipynb #--ignore=../_t_env/lib/python3.4/site-packages/molpx/notebooks/TICA_Fast_Folding_Analysis.ipynb --ignore=../_t_env/lib/python3.5/site-packages/molpx/notebooks/TICA_Fast_Folding_Analysis.ipynb
    - python -c "import shutil, os; shutil.copy('coverage.xml', os.path.expanduser('~'))" 
about:
  home: https://github.com/gph82/projection_explorer
  license: GNU Lesser Public License v3+
  summary: "molPX: Molecular Projection Explorer"


